version: '3.9'
x-default-logging:
  driver: json-file
  options:
    max-size: 50m
    max-file: '5'
x-default-labels:
  omni.quantum.tier: standard
  omni.quantum.critical: 'false'
services:
  listmonk:
    image: listmonk/listmonk:v4.1.0
    container_name: omni-listmonk
    command:
    - ./listmonk
    - --config
    - /listmonk/config.toml
    ports:
    - 9001:9000
    environment:
      LISTMONK_app__address: 0.0.0.0:9000
      LISTMONK_db__host: omni-listmonk-postgres
      LISTMONK_db__port: '5432'
      LISTMONK_db__database: listmonk
      LISTMONK_db__user: '{{ vault://secret/data/listmonk#db_user }}'
      LISTMONK_db__password: '{{ vault://secret/data/listmonk#db_password }}'
      LISTMONK_admin_username: '{{ vault://secret/data/listmonk#admin_username }}'
      LISTMONK_admin_password: '{{ vault://secret/data/listmonk#admin_password }}'
      LISTMONK_SMTP_HOST: omni-mailhog
      LISTMONK_SMTP_PORT: '1025'
      LISTMONK_SMTP_USER: '{{ vault://secret/data/smtp#username }}'
      LISTMONK_SMTP_PASSWORD: '{{ vault://secret/data/smtp#password }}'
    healthcheck:
      test:
      - CMD
      - wget
      - -qO-
      - http://localhost:9000/api/health
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '5'
    labels:
      omni.quantum.component: listmonk
      omni.quantum.tier: business
      omni.quantum.critical: 'false'
    depends_on:
      listmonk-postgres:
        condition: service_healthy
    volumes:
    - listmonk-data:/listmonk/uploads
    - ./config/listmonk-config.toml:/listmonk/config.toml:ro
    networks:
    - omni-quantum-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
    security_opt:
    - no-new-privileges:true
    cap_drop:
    - ALL
  listmonk-postgres:
    image: postgres:16-alpine
    container_name: omni-listmonk-postgres
    environment:
      POSTGRES_DB: listmonk
      POSTGRES_USER: '{{ vault://secret/data/listmonk#db_user }}'
      POSTGRES_PASSWORD: '{{ vault://secret/data/listmonk#db_password }}'
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U {{ vault://secret/data/listmonk#db_user }} -d listmonk
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '5'
    labels:
      omni.quantum.component: listmonk-postgres
      omni.quantum.tier: business
      omni.quantum.critical: 'false'
    volumes:
    - listmonk-postgres-data:/var/lib/postgresql/data
    networks:
    - omni-quantum-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
    security_opt:
    - no-new-privileges:true
    cap_drop:
    - ALL
volumes:
  listmonk-data: null
  listmonk-postgres-data: null
networks:
  omni-quantum-network:
    external: true
