server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://omni-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["omni.quantum.system"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_label_omni_name']
        target_label: service
      - source_labels: ['__meta_docker_container_label_omni_system']
        target_label: system_id
      - source_labels: ['__meta_docker_container_label_omni_tier']
        target_label: tier
