[app]
address = "0.0.0.0:9000"

[db]
host = "omni-listmonk-postgres"
port = 5432
database = "listmonk"
user = "{{ vault://secret/data/listmonk#db_user }}"
password = "{{ vault://secret/data/listmonk#db_password }}"
ssl_mode = "disable"

[smtp]
enabled = true
host = "omni-mailhog"
port = 1025
user = "{{ vault://secret/data/smtp#username }}"
password = "{{ vault://secret/data/smtp#password }}"
from = "omni@localhost"
